### ISSUE TITLE
Right hand corner button lines 

### ISSUE THREAD

**Issue by shravanisamala** [EducationShinyAppTeam/Assumptions#5]
I noticed that the three icons at the top right hand corner are separated by thin white lines. I looked at some of the other apps and they did not have these.

**Comment by lbednarczyk** [comment]
I think this is just something that happens with the color scheme because there isn't any argument that I can find that would cause it and other apps with this color also have it.

**Comment by neilhatfield** [comment]
Yes; this is a result of the color scheme. Any fixes will have to be made at a higher level than an app.
