### ISSUE TITLE
Rename Repo?

### ISSUE THREAD

**Issue by neilhatfield** [EducationShinyAppTeam/Assumptions#9]
This repository is named "Assumptions" and deals with the assumptions for linear regression. Would re-naming this repo be in the best interest in both clarity of repo and the URL for the app?

**Comment by rpc5102** [comment]
How about Assumptions for Linear Regression? What do you think @lbednarczyk?

**Comment by neilhatfield** [comment]
Let's go with Regression Assumptions. @rpc5102 will you please see that this change happens?

**Comment by neilhatfield** [comment]
Fixed.
